FROM python:3.8

WORKDIR /app
ENV NO_DICECLOUD=1
ENV TESTING=1

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install -r tests/requirements.txt

RUN mkdir shared

COPY . .

ENTRYPOINT pytest tests/
