FROM python:3.8

WORKDIR /app
ENV NO_DICECLOUD=1

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN mkdir shared

COPY . .

ENTRYPOINT bash scripts/gen_help.sh && pytest --cov=cogs5e --cov=cogsmisc --cov=utils --cov-report=xml:shared/coverage.xml tests/ test
