FROM python:3.7-stretch

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN mkdir shared

COPY . .

COPY docker/credentials-development.py credentials.py

ENTRYPOINT pytest --cov=cogs5e --cov=cogsmisc --cov=utils --cov-report=xml:shared/coverage.xml tests/ test
