name: LaunchDarkly Code References

on:
  push:
    branches:
      - master

jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: LaunchDarkly Code References
        uses: launchdarkly/find-code-references@v5
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          accessToken: ${{ secrets.LD_ACCESS_TOKEN }}
          projKey: avrae
