name: Test Disable AWS Alarm

on:
  workflow_dispatch:
  push:
    branches:
      - disable-aws-low-task-alarm-during-deploy

permissions:
  contents: read
  id-token: write

jobs:
  test-disable-aws-alarm:
    name: Test disable aws alarm
    runs-on: ubuntu-latest
    env:
      REGION: us-east-1
      ALARM_NAME: "Avrae Task Count Too Low"

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AVRAE_GITHUB_OIDC_ROLE_ARN }}
          role-session-name: "avrae-test-disable-aws-alarm"
          aws-region: ${{ env.REGION }}

      - name: Alarm state - before
        run: |
          aws cloudwatch describe-alarms \
            --alarm-names "$ALARM_NAME" \
            --region "$REGION" \
            --query "MetricAlarms[0].{Name:AlarmName,ActionsEnabled:ActionsEnabled,State:StateValue}" \
            --output table

      - name: Disable CloudWatch alarm actions
        run: |
          aws cloudwatch disable-alarm-actions \
            --alarm-names "$ALARM_NAME" \
            --region "$REGION"

      - name: Alarm state - disabled
        run: |
          aws cloudwatch describe-alarms \
            --alarm-names "$ALARM_NAME" \
            --region "$REGION" \
            --query "MetricAlarms[0].{Name:AlarmName,ActionsEnabled:ActionsEnabled,State:StateValue}" \
            --output table

      - name: Wait for checking alarm status
        run: sleep 120

      - name: Re-enable CloudWatch alarm actions
        if: always()
        run: |
          aws cloudwatch enable-alarm-actions \
            --alarm-names "$ALARM_NAME" \
            --region "$REGION"

      - name: Alarm state - after
        if: always()
        run: |
          aws cloudwatch describe-alarms \
            --alarm-names "$ALARM_NAME" \
            --region "$REGION" \
            --query "MetricAlarms[0].{Name:AlarmName,ActionsEnabled:ActionsEnabled,State:StateValue}" \
            --output table
